version: "3.9"
services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "https://yourbank.com"
    environment:
      - RASA_ENV=prod
  actions:
    image: rasa/rasa-sdk:3.6.0
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
    command:
      - start
      - --actions
      - actions