FROM rasa/rasa:3.6.0-full

WORKDIR /app

COPY . /app

# Install custom actions requirements
RUN pip install --no-cache-dir -r requirements.txt

USER 1001

CMD ["run", "--enable-api", "--cors", "*", "--debug"]